slug: desktop-measurement-overlays
title: "Desktop: measurement overlays"
description: Implement measure tool with distance readouts and snapping in the OCCT viewer bridge.
area: desktop-app
allowed_paths:
  - apps/desktop/src/**
  - apps/desktop/qml/**
labels:
  - codex
  - desktop
  - qt
acceptance:
  commands:
    - cmake --build --preset relwithdebinfo
  tests_expect:
    - Manual: capture two points, shows distance in units
  artifacts_expect:

dependencies:
  - desktop-viewer-bridge-occt

github:
  closing_keyword: True
created: 2025-09-23

