slug: mcp-schema-validation-middleware
title: "MCP: schema validation middleware"
description: Validate inputs/outputs using generated types.
area: mcp-server
allowed_paths:
  - apps/mcp-server/src/**
  - packages/schemas/**
  - packages/types/**
labels:
  - codex
  - mcp-server
acceptance:
  commands:
    - pnpm -w build
    - "pnpm -w test:mcp"
  tests_expect:
    - Contract tests pass; schema validation enforced
  artifacts_expect:

dependencies:
  - schemas-typegen-to-packages-types
  - mcp-registry-and-discovery
github:
  blocked_by:
    - schemas-typegen-to-packages-types
    - mcp-registry-and-discovery
  closing_keyword: True
created: 2025-09-21
