slug: security-secrets-scan-and-policies
title: "Security: secret scan & policies"
description: Enable secret scanning; document policies; mask logs.
area: security
allowed_paths:
  - ci/**
  - infra/**
labels:
  - codex
  - security
acceptance:
  commands:
    - echo 'scan run'
  tests_expect:

  artifacts_expect:

dependencies:

github:
  blocked_by:

  closing_keyword: True
created: 2025-09-21
