// Auto-generated by tools/codegen/generate-schema-types.mjs. DO NOT EDIT.

export interface CreateProjectInput {
  "seed"?: number;
  "template"?: string;
  "units": "mm" | "inch";
}

export interface CreateProjectOutput {
  "engine_versions": {
    "cam": string;
    "nest": string;
    "occt": string;
    "schemas": string;
    "wood": string;
  };
  "inputs_hash": string;
  "materials": Array<{
    "grain": string;
    "name": string;
    "thickness_mm": number;
  }>;
  "project_id": string;
  "revision_id": string;
  "seed": number;
  "template": string | null;
  "units": "mm" | "inch";
}

export interface ExportArtifactsInput {
  "destination"?: string;
  "format": "pdf" | "dxf" | "svg";
  "project_id": string;
  "revision_id"?: string;
  "seed"?: number;
}

export interface ExportArtifactsOutput {
  "artifact_path": string;
  "artifact_sha256": string;
  "bytes_written": number;
  "engine_versions": {
    "cam": string;
    "nest": string;
    "occt": string;
    "schemas": string;
    "wood": string;
  };
  "format": "pdf" | "dxf" | "svg";
  "inputs_hash": string;
  "project_id": string;
  "revision_id": string;
  "seed": number;
}

export interface ExtractCutlistInput {
  "project_id": string;
  "revision_id"?: string;
  "seed"?: number;
}

export interface ExtractCutlistOutput {
  "engine_versions": {
    "cam": string;
    "nest": string;
    "occt": string;
    "schemas": string;
    "wood": string;
  };
  "inputs_hash": string;
  "project_id": string;
  "revision_id": string;
  "rows": Array<{
    "grain": string;
    "length_mm": number;
    "material": string;
    "name": string;
    "part_id": string;
    "quantity": number;
    "thickness_mm": number;
    "width_mm": number;
  }>;
  "seed": number;
  "totals": {
    "material_totals": Array<{
      "count": number;
      "material": string;
    }>;
    "parts": number;
  };
}

export type ToolName = "create_project" | "export_artifacts" | "extract_cutlist";

export interface ToolInputMap {
  "create_project": CreateProjectInput;
  "export_artifacts": ExportArtifactsInput;
  "extract_cutlist": ExtractCutlistInput;
}

export interface ToolOutputMap {
  "create_project": CreateProjectOutput;
  "export_artifacts": ExportArtifactsOutput;
  "extract_cutlist": ExtractCutlistOutput;
}

export type ProvenanceKey = "seed" | "engine_versions" | "revision_id" | "inputs_hash";
